data:
  #path: "/home/oroz/gaussian-splatting/3DSSL-SS24_Generalizable3DHeadReconstruction/data"
  path: "/opt/data/269-single-timestep-EXP-1-head"
  dataloader_num_workers: 1 #10
  repeat_training_samples_num: 5 #50
  dataset_num_samples_train: "full"
  downscale_factor: 3
  rescale_factor_intrinsics: 0.5
  apply_alpha_map: False
  mask_Torso: True # Mask Torso also includes masking background
  use_color_correction: True
  upsample_flame_iterations: 2
  force_rebuild: False
  input_serials: ["222200049", "222200036"]
  use_depth: True #Check: model.use_depth
  use_monocular_depth: False 
logging:
  name: 'lc'
  log_error_images_every_n_steps: 200 # 0 means disabled

visualization:
  enabled: True

render:
  background_color: [1, 1, 1]                # white

model:
  name: gauss_predictor_mlp
  checkpoint: null
  use_depth: True #Check: data.use_depth
  model_parameters:
    input_image_features_dim: 779
    hidden_dim: 128 # 6
    positional_encoding_dim: 40
    latent_codes:
      enabled: False
    static_color: False
    positional_encoding_color: True

training:
  max_epochs: 100 
  lr: 0.0002 
  accumulate_grad_batches: 1 #4
  lambda_l1: 1
  lambda_ssim: 0.2
  lambda_lpips: 1
  lambda_depth: 1
  lambda_gaussian_normalization: 1


# pointcloud points:  (81418, 3) when upsample_flame_iterations:2
#8194 malek